[metadata]
description = "Counter-based data increment (I/O fixed: data_in[15:0], data_out[15:0])"

# Trojan core parameters
[crypto_vars.COUNTER_THRESHOLD]
type = "random_hex"
bits = 8
description = "Counter threshold for trigger"

[crypto_vars.DATA_INCREMENT]
type = "random_hex"
bits = 16
description = "Data increment when triggered"