[metadata]
host_file = "trojan6_barrel_shifter_host.v"
description = "Barrel shifter with state-based payload injection"

[params.DATA_WIDTH]
type = "choice"
values = [16, 24, 32, 48, 64]

# Crypto variables with parameter injection
[crypto_vars.TRIGGER_STATE_1]
type = "random_hex"
bits = 32
description = "First trigger state pattern"

[crypto_vars.TRIGGER_STATE_2]
type = "random_hex"
bits = 32
description = "Second trigger state pattern"

[crypto_vars.TRIGGER_STATE_3]
type = "random_hex"
bits = 32
description = "Third trigger state pattern"

[crypto_vars.TRIGGER_STATE_4]
type = "random_hex"
bits = 32
description = "Fourth trigger state pattern"

[crypto_vars.PAYLOAD_BITS]
type = "random_hex"
bits = 2
description = "Payload bits injected in LSB"