[metadata]
host_file = "trojan8_matrix_mult_host.v"
description = "Matrix multiplier with computation path injection"

# No structural params (I/O widths fixed in RTL); only three mask crypto vars
[crypto_vars.MASK_00FF]
type = "random_hex"
bits = 16
description = "Mask applied as t3 & MASK_00FF"

[crypto_vars.MASK_0F]
type = "random_hex"
bits = 8
description = "Mask applied to (a+c) lower 4 bits"

[crypto_vars.MASK_F0F0]
type = "random_hex"
bits = 16
description = "Mask applied in final XOR"