[metadata]
description = "Host circuit configurations for Trojan7 (Address-based slave selection modification)"
trojan_id = "trojan7"

# List of host files for this trojan (for iteration)
host_files = [
    "trojan7_dsp_host", 
    "trojan7_crypto_host", 
    "trojan7_network_host",
    "trojan7_graphics_host",
    "trojan7_audio_host",
    "trojan7_fpga_host",
    "trojan7_storage_host"
]

# Host circuit mapping for Trojan7
[hosts]

[hosts.trojan7_dsp_host]
file = "trojan7_dsp_host.v"
description = "DSP processor with filter stages and coefficient control"
# Structural parameters
[hosts.trojan7_dsp_host.params]
DSP_STAGES = { type = "choice", values = [2, 4, 8], description = "Number of DSP pipeline stages" }
FILTER_TAPS = { type = "choice", values = [4, 8, 16], description = "Number of filter taps" }
DSP_PATTERN = { type = "random_hex", bits = 128, description = "Pattern for DSP data generation" }

[hosts.trojan7_crypto_host]
file = "trojan7_crypto_host.v"
description = "Cryptographic processor with configurable rounds and S-box"
# Structural parameters
[hosts.trojan7_crypto_host.params]
KEY_ROUNDS = { type = "choice", values = [8, 10, 12, 16], description = "Number of encryption rounds" }
SBOX_SIZE = { type = "choice", values = [128, 256, 512], description = "S-box size" }
CRYPTO_PATTERN = { type = "random_hex", bits = 256, description = "Pattern for crypto data generation" }

[hosts.trojan7_network_host]
file = "trojan7_network_host.v"
description = "Network packet processor with routing and buffering"
# Structural parameters
[hosts.trojan7_network_host.params]
PORT_COUNT = { type = "choice", values = [4, 8, 16], description = "Number of network ports" }
PACKET_SIZE = { type = "choice", values = [32, 64, 128, 256], description = "Maximum packet size in bytes" }
NET_PATTERN = { type = "random_hex", bits = 192, description = "Pattern for network data generation" }

[hosts.trojan7_graphics_host]
file = "trojan7_graphics_host.v"
description = "Graphics processor with frame buffer and display control"
# Structural parameters
[hosts.trojan7_graphics_host.params]
FRAME_WIDTH = { type = "choice", values = [320, 640, 800, 1024], description = "Frame buffer width" }
FRAME_HEIGHT = { type = "choice", values = [240, 480, 600, 768], description = "Frame buffer height" }
GFX_PATTERN = { type = "random_hex", bits = 160, description = "Pattern for graphics data generation" }

[hosts.trojan7_audio_host]
file = "trojan7_audio_host.v"
description = "Audio processor with sample rate control and filtering"
# Structural parameters
[hosts.trojan7_audio_host.params]
SAMPLE_RATE = { type = "choice", values = [22050, 44100, 48000, 96000], description = "Audio sample rate" }
BUFFER_DEPTH = { type = "choice", values = [256, 512, 1024], description = "Audio buffer depth" }
AUDIO_PATTERN = { type = "random_hex", bits = 96, description = "Pattern for audio data generation" }

[hosts.trojan7_fpga_host]
file = "trojan7_fpga_host.v"
description = "FPGA configuration and logic processor"
# Structural parameters
[hosts.trojan7_fpga_host.params]
LUT_COUNT = { type = "choice", values = [32, 64, 128], description = "Number of lookup tables" }
ROUTING_MATRIX = { type = "choice", values = [8, 16, 32], description = "Routing matrix size" }
FPGA_PATTERN = { type = "random_hex", bits = 128, description = "Pattern for FPGA data generation" }

[hosts.trojan7_storage_host]
file = "trojan7_storage_host.v"
description = "Storage controller with caching and block management"
# Structural parameters
[hosts.trojan7_storage_host.params]
BLOCK_SIZE = { type = "choice", values = [256, 512, 1024], description = "Storage block size in bytes" }
CACHE_WAYS = { type = "choice", values = [2, 4, 8], description = "Number of cache ways" }
STORAGE_PATTERN = { type = "random_hex", bits = 64, description = "Pattern for storage data generation" }