[metadata]
host_file = "trojan7_axi_host.v"
description = "AXI-lite with wishbone address/data trigger"

[params.DATA_WIDTH]
type = "choice"
values = [16, 24, 32, 48, 64]

[params.SLAVE_SEL_WIDTH]
type = "choice"
values = [4, 8, 12, 16]

# Crypto variables with parameter injection
[crypto_vars.WB_DATA_TRIGGER]
type = "random_hex"
bits = 32
description = "Wishbone data trigger pattern (wb_data_i)"

[crypto_vars.S0_DATA_TRIGGER]
type = "random_hex"
bits = 32
description = "Slave 0 data trigger pattern (s0_data_i)"

[crypto_vars.XOR_MASK]
type = "random_hex"
bits = 4
description = "XOR mask applied to slave select when triggered"