[metadata]
description = "Host circuit configurations for Trojan0 (LFSR-based trojan with XOR mask)"
trojan_id = "trojan0"

# List of host files for this trojan (for iteration)
host_files = [
    "trojan0_datapath_host", 
    "trojan0_pwm_host", 
    "trojan0_counter_host",
    "trojan0_crypto_host",
    "trojan0_network_host", 
    "trojan0_spi_host",
    "trojan0_cache_host",
    "trojan0_uart_host",
    "trojan0_timer_host",
    "trojan0_fifo_host"
]

# Host circuit mapping for Trojan0
[hosts]

[hosts.trojan0_datapath_host]
file = "trojan0_datapath_host.v"
description = "Simple datapath with ALU operations"
# Structural parameters (adjustable circuit complexity)
[hosts.trojan0_datapath_host.params]
DATA_WIDTH = { type = "choice", values = [8, 12, 16, 20], description = "Data width for ALU operations" }

# Crypto parameters for host circuit
[hosts.trojan0_datapath_host.crypto_vars]
KEY_INIT = { type = "random_hex", bits = 128, description = "Initial key generation value" }

[hosts.trojan0_pwm_host]
file = "trojan0_pwm_host.v"
description = "PWM generator with configurable duty cycle and frequency"
# Structural parameters
[hosts.trojan0_pwm_host.params]
PWM_WIDTH = { type = "choice", values = [8, 10, 12], description = "PWM counter width" }
PRESCALER = { type = "choice", values = [4, 8, 16], description = "Clock prescaler value" }
# Crypto parameters
[hosts.trojan0_pwm_host.crypto_vars]
KEY_INIT = { type = "random_hex", bits = 128, description = "PWM key generator seed" }

[hosts.trojan0_counter_host]
file = "trojan0_counter_host.v"
description = "Counter circuit with overflow and pulse generation" 
# Structural parameters
[hosts.trojan0_counter_host.params]
COUNT_WIDTH = { type = "choice", values = [8, 10, 12, 14], description = "Counter bit width" }
PERIOD = { type = "range", min = 50, max = 200, description = "Pulse generation period" }

[hosts.trojan0_counter_host.crypto_vars]
KEY_INIT = { type = "random_hex", bits = 128, description = "Counter key generator seed" }

[hosts.trojan0_crypto_host]
file = "trojan0_crypto_host.v"
description = "Cryptographic processor with encryption rounds"
# Structural parameters
[hosts.trojan0_crypto_host.params]
DATA_WIDTH = { type = "choice", values = [64, 128, 256], description = "Cipher block size" }
ROUND_COUNT = { type = "choice", values = [4, 6, 8, 12], description = "Number of encryption rounds" }
# Crypto parameters
[hosts.trojan0_crypto_host.crypto_vars]
KEY_INIT = { type = "random_hex", bits = 128, description = "Crypto key generator seed" }

[hosts.trojan0_network_host]
file = "trojan0_network_host.v"
description = "Network packet processor with routing"
# Structural parameters
[hosts.trojan0_network_host.params]
PACKET_SIZE = { type = "choice", values = [32, 64, 128], description = "Network packet size in bytes" }
BUFFER_DEPTH = { type = "choice", values = [8, 16, 32, 64], description = "Packet buffer depth" }
# Crypto parameters
[hosts.trojan0_network_host.crypto_vars]
KEY_INIT = { type = "random_hex", bits = 128, description = "Network key generator seed" }

[hosts.trojan0_spi_host]
file = "trojan0_spi_host.v"
description = "SPI Controller with configurable data width"
# Structural parameters
[hosts.trojan0_spi_host.params]
DATA_WIDTH = { type = "choice", values = [8, 16], description = "SPI data width" }
CLOCK_DIV = { type = "choice", values = [4, 8, 16], description = "SPI clock divider" }
# Crypto parameters
[hosts.trojan0_spi_host.crypto_vars]
KEY_INIT = { type = "random_hex", bits = 128, description = "SPI key generator seed" }

[hosts.trojan0_cache_host]
file = "trojan0_cache_host.v"
description = "Cache memory with tag-based lookup"
# Structural parameters
[hosts.trojan0_cache_host.params]
CACHE_SIZE = { type = "choice", values = [8, 16, 32], description = "Number of cache lines (reduced)" }
DATA_WIDTH = { type = "choice", values = [16, 32], description = "Cache line data width (reduced)" }
TAG_WIDTH = { type = "choice", values = [4, 6, 8], description = "Cache tag width (reduced)" }
# Crypto parameters
[hosts.trojan0_cache_host.crypto_vars]
KEY_INIT = { type = "random_hex", bits = 128, description = "Cache key generator seed" }

[hosts.trojan0_uart_host]
file = "trojan0_uart_host.v"
description = "UART transceiver with configurable baud rate"
# Structural parameters
[hosts.trojan0_uart_host.params]
BAUD_DIV = { type = "choice", values = [52, 104, 208, 416], description = "Baud rate divisor (higher = slower)" }
DATA_BITS = { type = "choice", values = [7, 8], description = "Number of data bits" }
# Crypto parameters
[hosts.trojan0_uart_host.crypto_vars]
KEY_INIT = { type = "random_hex", bits = 128, description = "UART key generator seed" }

[hosts.trojan0_timer_host]
file = "trojan0_timer_host.v"
description = "Programmable timer with prescaler"
# Structural parameters
[hosts.trojan0_timer_host.params]
TIMER_WIDTH = { type = "choice", values = [16, 24, 32], description = "Timer counter width" }
PRESCALER = { type = "choice", values = [100, 500, 1000, 5000], description = "Clock prescaler value" }
# Crypto parameters
[hosts.trojan0_timer_host.crypto_vars]
KEY_INIT = { type = "random_hex", bits = 128, description = "Timer key generator seed" }

[hosts.trojan0_fifo_host]
file = "trojan0_fifo_host.v"
description = "FIFO buffer with configurable depth"
# Structural parameters
[hosts.trojan0_fifo_host.params]
DATA_WIDTH = { type = "choice", values = [8, 16], description = "FIFO data width" }
ADDR_WIDTH = { type = "choice", values = [3, 4], description = "Address width (DEPTH = 2^ADDR_WIDTH)" }
# Crypto parameters
[hosts.trojan0_fifo_host.crypto_vars]
KEY_INIT = { type = "random_hex", bits = 128, description = "FIFO key generator seed" }