[metadata]
host_file = "trojan9_cordic_host.v"
description = "CORDIC processor with mode-based computation alteration"

[crypto_vars.COMPUTATION_BIAS]
type = "random_hex"
bits = 16
description = "Bias value added to computation results"

