[metadata]
description = "Host circuit configurations for Trojan2 (Sequence-based trigger with force reset)"
trojan_id = "trojan2"

# List of host files for this trojan (for iteration)
host_files = [
]

# Host circuit mapping for Trojan2
[hosts]