[metadata]
description = "Arithmetic computation with mask operations (I/O fixed: a[7:0], b[7:0], c[7:0], d[7:0], e[7:0], sel[2:0], y[15:0])"

# No structural params (I/O widths fixed in RTL); only three mask crypto vars
[crypto_vars.MASK_00FF]
type = "random_hex"
bits = 16
description = "Mask applied as t3 & MASK_00FF"

[crypto_vars.MASK_0F]
type = "random_hex"
bits = 8
description = "Mask applied to (a+c) lower 4 bits"

[crypto_vars.MASK_F0F0]
type = "random_hex"
bits = 16
description = "Mask applied in final XOR"