[metadata]
description = "Host circuit configurations for Trojan8 (Multi-input arithmetic computation modification)"
trojan_id = "trojan8"

# List of host files for this trojan (for iteration)
host_files = [
    "trojan8_dsp0_host"
]

# Host circuit mapping for Trojan8
[hosts]

[hosts.trojan8_dsp0_host]
file = "trojan8_dsp0_host.v"
description = "DSP processor with signal processing operations"
[hosts.trojan8_dsp0_host.params]
# Host-specific parameters
INPUT_WIDTH = { type = "choice", values = [4, 6, 8, 12], description = "Input width"}
PIPELINE_STAGES = { type = "choice", values = [3, 4, 5, 6, 7], description = "Number of pipeline stages"}
DSP_SEED = { type = "random_hex", bits = "INPUT_WIDTH", description = "DSP key generator seed" }
# Trojan core parameters
TROJ_MASK1 = { type = "random_hex", bits = "INPUT_WIDTH*2", description = "Trojan mask 1"}
TROJ_MASK2 = { type = "random_hex", bits = "INPUT_WIDTH", description = "Trojan mask 2"}
TROJ_MASK3 = { type = "random_hex", bits = "INPUT_WIDTH*2", description = "Trojan mask 3"}