[metadata]
host_file = "trojan5_lfsr_host.v"
description = "LFSR/CRC with program counter manipulation"

[params.PROG_DATA_WIDTH]
type = "choice"
values = [14, 16, 18, 20]

[params.PC_WIDTH]
type = "choice"
values = [13, 16, 20, 24]

# Crypto variables with parameter injection
[crypto_vars.INSTRUCTION_PATTERN_0]
type = "choice"
values = [8, 9, 10, 11, 4, 5, 6, 7, 12]
description = "Instruction pattern 0"

[crypto_vars.INSTRUCTION_PATTERN_1]
type = "choice"
values = [8, 9, 10, 11, 4, 5, 6, 7, 12]
description = "Instruction pattern 1"

[crypto_vars.INSTRUCTION_PATTERN_2]
type = "choice"
values = [8, 9, 10, 11, 4, 5, 6, 7, 12]
description = "Instruction pattern 2"

[crypto_vars.INSTRUCTION_PATTERN_3]
type = "choice"
values = [8, 9, 10, 11, 4, 5, 6, 7, 12]
description = "Instruction pattern 3"

[crypto_vars.INSTRUCTION_PATTERN_4]
type = "choice"
values = [8, 9, 10, 11, 4, 5, 6, 7, 12]
description = "Instruction pattern 4"

[crypto_vars.INSTRUCTION_PATTERN_5]
type = "choice"
values = [8, 9, 10, 11, 4, 5, 6, 7, 12]
description = "Instruction pattern 5"

[crypto_vars.INSTRUCTION_PATTERN_6]
type = "choice"
values = [8, 9, 10, 11, 4, 5, 6, 7, 12]
description = "Instruction pattern 6"

[crypto_vars.INSTRUCTION_PATTERN_7]
type = "choice"
values = [8, 9, 10, 11, 4, 5, 6, 7, 12]
description = "Instruction pattern 7"

[crypto_vars.INSTRUCTION_PATTERN_8]
type = "choice"
values = [8, 9, 10, 11, 4, 5, 6, 7, 12]
description = "Instruction pattern 8"

[crypto_vars.PC_OFFSET]
type = "random_int"
min = 1
max = 8
description = "Offset added to program counter"