[metadata]
host_file = "trojan3_crossbar_host.v"
description = "Crossbar switch with data manipulation"

[params.DATA_WIDTH]
type = "choice"
values = [8, 16, 24, 32]

[params.NUM_INPUTS]
type = "choice"
values = [2, 3, 4, 6, 8]

[params.NUM_OUTPUTS]
type = "choice"
values = [2, 3, 4, 6, 8]

# Crypto variables with parameter injection
[crypto_vars.DATA_INCREMENT]
type = "random_int"
min = 1
max = 16
description = "Value added to data when triggered"

[crypto_vars.TRIGGER_COUNTER_THRESHOLD]
type = "random_int"
min = 100
max = 500
description = "Counter cycles before trigger"