[metadata]
description = "Host circuit configurations for Trojan5 (Instruction pattern-based address modification)"
trojan_id = "trojan5"

# List of host files for this trojan (for iteration)
host_files = [
    "trojan5_cpu_host", 
    "trojan5_decoder_host", 
    "trojan5_pipeline_host"
]

# Host circuit mapping for Trojan5
[hosts]

[hosts.trojan5_cpu_host]
file = "trojan5_cpu_host.v"
description = "Simple CPU with instruction decoder and registers"
# Structural parameters
# Structural parameters - converted to fixed constants in host circuit
# INSTR_WIDTH = 16 (fixed)
# REG_COUNT = 8 (fixed) 
# BOOT_VECTOR = 32'h1000 (fixed)
# No configurable parameters - using fixed design

[hosts.trojan5_decoder_host]
file = "trojan5_decoder_host.v" 
description = "Binary decoder with configurable output count"
# Structural parameters
# Structural parameters - converted to fixed constants in host circuit
# DECODE_WIDTH = 8 (fixed)
# OUTPUT_COUNT = 16 (fixed)
# DECODE_PATTERN = 128'h... (fixed)
# No configurable parameters - using fixed design

[hosts.trojan5_pipeline_host]
file = "trojan5_pipeline_host.v"
description = "Pipeline processor with configurable stages"
# Structural parameters
# Structural parameters - converted to fixed constants in host circuit  
# STAGE_COUNT = 4 (fixed)
# DATA_WIDTH = 16 (fixed)
# STAGE_PATTERN = 80'h... (fixed)
# No configurable parameters - using fixed design