[metadata]
description = "Host circuit configurations for Trojan7 (Address-based slave selection modification)"
trojan_id = "trojan7"

# List of host files for this trojan (for iteration)
host_files = [
    "trojan7_wishbone0_host",
    "trojan7_wishbone1_host",
    "trojan7_axi0_host"
]

# Host circuit mapping for Trojan7
[hosts]

[hosts.trojan7_wishbone0_host]
file = "trojan7_wishbone0_host.v"
description = "Wishbone bus arbiter with slave selection (192-bit pattern)"
# Structural parameters
[hosts.trojan7_wishbone0_host.params]
TIMEOUT_CYCLES = { type = "choice", values = [8, 16, 32, 64], description = "Timeout for transactions" }
# Crypto parameters
[hosts.trojan7_wishbone0_host.crypto_vars]
WB_PATTERN = { type = "random_hex", bits = 192, description = "Pattern for wishbone data generation" }


[hosts.trojan7_wishbone1_host]
file = "trojan7_wishbone1_host.v"
description = "Wishbone bus arbiter with modified access logic (192-bit pattern)"
# Structural parameters
[hosts.trojan7_wishbone1_host.params]
TIMEOUT_CYCLES = { type = "choice", values = [8, 16, 32, 64], description = "Timeout for transactions" }
# Crypto parameters
[hosts.trojan7_wishbone1_host.crypto_vars]
WB_PATTERN = { type = "random_hex", bits = 192, description = "Pattern for wishbone data generation" }


[hosts.trojan7_axi0_host]
file = "trojan7_axi0_host.v"
description = "AXI4 interconnect with address decoding (no external parameters)"
# No external parameters - AXI_PATTERN is defined as localparam inside the module