[metadata]
description = "Host circuit configurations for Trojan9 (Mode-based arithmetic computations)"
trojan_id = "trojan9"

# List of host files for this trojan (for iteration)
host_files = [
    "trojan9_compression_host",
    "trojan9_cordic_host",
    "trojan9_signal_host",
    "trojan9_alu_host"
]

# Host circuit mapping for Trojan9
[hosts]

[hosts.trojan9_compression_host]
file = "trojan9_compression_host.v"
description = "Data compression unit with multiple algorithms"
# Crypto parameters
[hosts.trojan9_compression_host.crypto_vars]
COMP_PATTERN = { type = "random_hex", bits = 56, description = "Compression data pattern" }


[hosts.trojan9_cordic_host]
file = "trojan9_cordic_host.v"
description = "CORDIC processor for trigonometric and hyperbolic functions"
# Structural parameters
[hosts.trojan9_cordic_host.params]
ATAN_CONST = { type = "choice", values = [13380, 16644, 20740], description = "ATAN approximation constant" }
# Crypto parameters
[hosts.trojan9_cordic_host.crypto_vars]
CORDIC_PATTERN = { type = "random_hex", bits = 128, description = "CORDIC data pattern" }


[hosts.trojan9_signal_host]
file = "trojan9_signal_host.v"
description = "Signal processing unit with filter modes"
# Crypto parameters
[hosts.trojan9_signal_host.crypto_vars]
SIG_PATTERN = { type = "random_hex", bits = 192, description = "Signal processing data pattern" }


[hosts.trojan9_alu_host]
file = "trojan9_alu_host.v"
description = "Corrected ALU-based vector processor with subtle trojan"
# Crypto parameters
[hosts.trojan9_alu_host.crypto_vars]
VECTOR_PATTERN = { type = "random_hex", bits = 80, description = "Vector data pattern" }
