[metadata]
description = "LFSR-based trojan with XOR mask (I/O bitwidths fixed: key[127:0], load[63:0])"

# Trojan core parameters (non-I/O tunables)
[crypto_vars.LOAD_XOR_MASK]
type = "random_hex"
bits = 64
description = "XOR mask applied to load output"

[crypto_vars.INIT_VALUE] 
type = "random_hex"
bits = 20
description = "LFSR initial value"