[metadata]
description = "Data-triggered slave select XOR (I/O fixed: wb_addr_i[31:0], wb_data_i[31:0], s0_data_i[31:0], slv_sel[3:0])"

# Trojan core parameters
[crypto_vars.WB_DATA_TRIGGER]
type = "random_hex"
bits = 32
description = "Wishbone data trigger pattern (wb_data_i)"

[crypto_vars.S0_DATA_TRIGGER]
type = "random_hex"
bits = 32
description = "Slave 0 data trigger pattern (s0_data_i)"

[crypto_vars.XOR_MASK]
type = "random_hex"
bits = 4
description = "XOR mask applied to slave select when triggered"