[metadata]
description = "Host circuit configurations for Trojan4 (LFSR-based key leakage)"
trojan_id = "trojan4"

# List of host files for this trojan (for iteration)
host_files = [
    "trojan4_crypto0_host", 
    "trojan4_crypto1_host",
    "trojan4_rsa0_host",
    "trojan4_rsa1_host"
]

# Host circuit mapping for Trojan4
[hosts]

[hosts.trojan4_crypto0_host]
file = "trojan4_crypto0_host.v"
description = "Block cipher encryption with configurable rounds"
# Crypto parameters
[hosts.trojan4_crypto0_host.crypto_vars]
IV_SEED = { type = "random_hex", bits = 128, description = "Initialization vector seed" }


[hosts.trojan4_crypto1_host]
file = "trojan4_crypto1_host.v"
description = "Block cipher encryption with configurable rounds"
# Crypto parameters
[hosts.trojan4_crypto1_host.crypto_vars]
IV_SEED = { type = "random_hex", bits = 128, description = "Initialization vector seed" }


[hosts.trojan4_rsa0_host]
file = "trojan4_rsa0_host.v"
description = "RSA modular exponentiation with configurable modulus width"
# Crypto parameters
[hosts.trojan4_rsa0_host.crypto_vars]
PRIME_SEED = { type = "random_hex", bits = 128, description = "Prime number generation seed" }


[hosts.trojan4_rsa1_host]
file = "trojan4_rsa1_host.v"
description = "RSA modular exponentiation with configurable modulus width"
# Crypto parameters
[hosts.trojan4_rsa1_host.crypto_vars]
PRIME_SEED = { type = "random_hex", bits = 128, description = "Prime number generation seed" }
