[metadata]
description = "Host circuit configurations for Trojan1 (Counter-based trigger)"
trojan_id = "trojan1"

# List of host files for this trojan (for iteration)
host_files = [
    "trojan1_fsm_host", 
    "trojan1_timer_host", 
    "trojan1_shifter_host",
    "trojan1_counter_host",
    "trojan1_memory_host", 
    "trojan1_alu_host",
    "trojan1_spi_host",
    "trojan1_pwm_host",
    "trojan1_fifo_host",
    "trojan1_uart_host"
]

# Host circuit mapping for Trojan1
[hosts]

[hosts.trojan1_fsm_host]
file = "trojan1_fsm_host.v"
description = "Finite State Machine with data processing"
# Structural parameters
[hosts.trojan1_fsm_host.params]
DATA_WIDTH = { type = "choice", values = [8, 12, 16, 24], description = "State and data width" }
# Crypto parameters
[hosts.trojan1_fsm_host.crypto_vars]
INIT_SEED = { type = "random_hex", bits = 8, description = "Initial seed for r1 signal generation" }

[hosts.trojan1_timer_host]
file = "trojan1_timer_host.v" 
description = "Timer circuit with timeout and pause functionality"
# Structural parameters
[hosts.trojan1_timer_host.params]
TIMER_WIDTH = { type = "choice", values = [8, 10, 12, 14], description = "Timer counter bit width" }
TIMEOUT_VAL = { type = "range", min = 200, max = 1000, description = "Timer timeout value" }
# Crypto parameters
[hosts.trojan1_timer_host.crypto_vars]
R1_PATTERN = { type = "random_hex", bits = 16, description = "Pattern for r1 signal generation" }

[hosts.trojan1_shifter_host]
file = "trojan1_shifter_host.v"
description = "Barrel shifter with configurable shift steps"
# Structural parameters
[hosts.trojan1_shifter_host.params]
DATA_WIDTH = { type = "choice", values = [12, 16, 20, 24], description = "Shift register width" }
SHIFT_STEPS = { type = "choice", values = [2, 4, 6, 8], description = "Number of shift steps per operation" }
# Crypto parameters
[hosts.trojan1_shifter_host.crypto_vars]
R1_SEED = { type = "random_hex", bits = 32, description = "LFSR seed for r1 signal generation" }

[hosts.trojan1_counter_host]
file = "trojan1_counter_host.v"
description = "Counter with configurable direction and limits"
# Structural parameters
[hosts.trojan1_counter_host.params]
COUNTER_WIDTH = { type = "choice", values = [8, 10, 12, 14], description = "Counter bit width" }
COUNT_LIMIT = { type = "range", min = 512, max = 4096, description = "Maximum count value" }
# Crypto parameters
[hosts.trojan1_counter_host.crypto_vars]
R1_INIT = { type = "random_hex", bits = 24, description = "LFSR initialization value for r1 generation" }

[hosts.trojan1_memory_host]
file = "trojan1_memory_host.v"
description = "Memory array with read/write operations"
# Structural parameters
[hosts.trojan1_memory_host.params]
DATA_WIDTH = { type = "choice", values = [12, 16, 20, 24], description = "Memory data width" }
ADDR_WIDTH = { type = "choice", values = [4, 5, 6, 7], description = "Memory address width" }
# Crypto parameters
[hosts.trojan1_memory_host.crypto_vars]
R1_KEY = { type = "random_hex", bits = 32, description = "Key for r1 counter-based generation" }

[hosts.trojan1_alu_host]
file = "trojan1_alu_host.v"
description = "Arithmetic Logic Unit with multiple operations"
# Structural parameters
[hosts.trojan1_alu_host.params]
DATA_WIDTH = { type = "choice", values = [12, 16, 20, 24], description = "ALU operand width" }
# Crypto parameters
[hosts.trojan1_alu_host.crypto_vars]
R1_PATTERN = { type = "random_hex", bits = 16, description = "Pattern for r1 shift-based generation" }

[hosts.trojan1_spi_host]
file = "trojan1_spi_host.v"
description = "SPI master controller with configurable clock"
# Structural parameters
[hosts.trojan1_spi_host.params]
DATA_WIDTH = { type = "choice", values = [8, 12, 16], description = "SPI data frame width" }
CLK_DIV = { type = "choice", values = [8, 16, 32, 64], description = "SPI clock divider ratio" }
# Crypto parameters
[hosts.trojan1_spi_host.crypto_vars]
R1_SEED = { type = "random_hex", bits = 20, description = "LFSR seed for r1 generation" }

[hosts.trojan1_pwm_host]
file = "trojan1_pwm_host.v"
description = "PWM generator with multiple channels"
# Structural parameters
[hosts.trojan1_pwm_host.params]
PWM_WIDTH = { type = "choice", values = [8, 10, 12, 14], description = "PWM counter resolution" }
PWM_CHANNELS = { type = "choice", values = [2, 3, 4], description = "Number of PWM channels" }
# Crypto parameters
[hosts.trojan1_pwm_host.crypto_vars]
R1_INIT = { type = "random_hex", bits = 12, description = "Initial value for r1 counter generation" }

[hosts.trojan1_fifo_host]
file = "trojan1_fifo_host.v"
description = "FIFO buffer with configurable depth"
# Structural parameters
[hosts.trojan1_fifo_host.params]
DATA_WIDTH = { type = "choice", values = [8, 12, 16, 20], description = "FIFO data width" }
DEPTH = { type = "choice", values = [8, 16, 32, 64], description = "FIFO depth (power of 2)" }
ADDR_WIDTH = { type = "choice", values = [3, 4, 5, 6], description = "FIFO address width (log2 depth)" }
# Crypto parameters
[hosts.trojan1_fifo_host.crypto_vars]
R1_KEY = { type = "random_hex", bits = 28, description = "Key for r1 rotating generation" }

[hosts.trojan1_uart_host]
file = "trojan1_uart_host.v"
description = "UART transceiver with configurable baud rate"
# Structural parameters
[hosts.trojan1_uart_host.params]
BAUD_DIV = { type = "choice", values = [52, 104, 208, 416], description = "Baud rate divider (50MHz base)" }
DATA_BITS = { type = "choice", values = [7, 8, 9], description = "Number of data bits per frame" }
STOP_BITS = { type = "choice", values = [1, 2], description = "Number of stop bits" }
# Crypto parameters
[hosts.trojan1_uart_host.crypto_vars]
R1_SEED = { type = "random_hex", bits = 18, description = "Seed for r1 multi-phase shift register" }