[metadata]
description = "Instruction pattern-based PC manipulation (I/O fixed: prog_dat_i[13:0], pc_reg[12:0], prog_adr_o[12:0])"

# Trojan core parameters
[crypto_vars.INSTRUCTION_PATTERN_0]
type = "choice"
values = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
description = "Instruction pattern 0 (4-bit)"

[crypto_vars.INSTRUCTION_PATTERN_1]
type = "choice"
values = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
description = "Instruction pattern 1 (4-bit)"

[crypto_vars.INSTRUCTION_PATTERN_2]
type = "choice"
values = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
description = "Instruction pattern 2 (4-bit)"

[crypto_vars.INSTRUCTION_PATTERN_3]
type = "choice"
values = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
description = "Instruction pattern 3 (4-bit)"

[crypto_vars.INSTRUCTION_PATTERN_4]
type = "choice"
values = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
description = "Instruction pattern 4 (4-bit)"

[crypto_vars.INSTRUCTION_PATTERN_5]
type = "choice"
values = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
description = "Instruction pattern 5 (4-bit)"

[crypto_vars.INSTRUCTION_PATTERN_6]
type = "choice"
values = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
description = "Instruction pattern 6 (4-bit)"

[crypto_vars.INSTRUCTION_PATTERN_7]
type = "choice"
values = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
description = "Instruction pattern 7 (4-bit)"

[crypto_vars.INSTRUCTION_PATTERN_8]
type = "choice"
values = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
description = "Instruction pattern 8 (4-bit)"

[crypto_vars.INSTRUCTION_PATTERN_9]
type = "choice"
values = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
description = "Instruction pattern 9 (4-bit)"

[crypto_vars.PC_OFFSET]
type = "random_int"
min = 1
max = 8191
description = "Offset added to program counter (13-bit)"