[metadata]
description = "State-based payload trigger (I/O fixed: m0_data_o[31:0], i_s15_data_o[31:0], i_s15_data_o_TrojanPayload[31:0])"

# Trojan core parameters
[crypto_vars.TRIGGER_STATE_1]
type = "random_hex"
bits = 32
description = "First trigger state pattern"

[crypto_vars.TRIGGER_STATE_2]
type = "random_hex"
bits = 32
description = "Second trigger state pattern"

[crypto_vars.TRIGGER_STATE_3]
type = "random_hex"
bits = 32
description = "Third trigger state pattern"

[crypto_vars.TRIGGER_STATE_4]
type = "random_hex"
bits = 32
description = "Fourth trigger state pattern"

[crypto_vars.PAYLOAD_BITS]
type = "choice"
values = [0, 1, 2, 3]
description = "Payload bits configuration (2-bit)"