[metadata]
description = "Host circuit configurations for Trojan6 (State-based payload injection)"
trojan_id = "trojan6"

# List of host files for this trojan (for iteration)
host_files = [
    "trojan6_processor0_host",
    "trojan6_processor1_host", 
    "trojan6_bus0_host",
    "trojan6_bus1_host"
]

# Host circuit mapping for Trojan6
[hosts]

[hosts.trojan6_processor0_host]
file = "trojan6_processor0_host.v"
description = "Processor with instruction execution and register file (128-bit LFSR)"
# Crypto parameters
[hosts.trojan6_processor0_host.crypto_vars]
LFSR_INIT = { type = "random_hex", bits = 128, description = "128-bit LFSR initialization value" }


[hosts.trojan6_processor1_host]
file = "trojan6_processor1_host.v"
description = "Processor with instruction execution and register file (32-bit LFSR)"
# Crypto parameters
[hosts.trojan6_processor1_host.crypto_vars]
LFSR_INIT = { type = "random_hex", bits = 32, description = "32-bit LFSR initialization value" }


[hosts.trojan6_bus0_host]
file = "trojan6_bus0_host.v"
description = "Bus arbiter with 4 slave registers and 128-bit LFSR"
# Crypto parameters
[hosts.trojan6_bus0_host.crypto_vars]
REG1_INIT = { type = "random_hex", bits = 128, description = "Slave register 1 initialization value" }
REG2_INIT = { type = "random_hex", bits = 128, description = "Slave register 2 initialization value" }
REG3_INIT = { type = "random_hex", bits = 128, description = "Slave register 3 initialization value" }
REG4_INIT = { type = "random_hex", bits = 128, description = "Slave register 4 initialization value" }
LFSR_INIT = { type = "random_hex", bits = 128, description = "128-bit LFSR initialization value" }


[hosts.trojan6_bus1_host]
file = "trojan6_bus1_host.v"
description = "Bus arbiter with 8 slave registers and 32-bit LFSR"
# Crypto parameters
[hosts.trojan6_bus1_host.crypto_vars]
REG1_INIT = { type = "random_hex", bits = 128, description = "Slave register 1 initialization value" }
REG2_INIT = { type = "random_hex", bits = 128, description = "Slave register 2 initialization value" }
REG3_INIT = { type = "random_hex", bits = 128, description = "Slave register 3 initialization value" }
REG4_INIT = { type = "random_hex", bits = 128, description = "Slave register 4 initialization value" }
REG5_INIT = { type = "random_hex", bits = 128, description = "Slave register 5 initialization value" }
REG6_INIT = { type = "random_hex", bits = 128, description = "Slave register 6 initialization value" }
REG7_INIT = { type = "random_hex", bits = 128, description = "Slave register 7 initialization value" }
REG8_INIT = { type = "random_hex", bits = 128, description = "Slave register 8 initialization value" }
LFSR_INIT = { type = "random_hex", bits = 32, description = "32-bit LFSR initialization value" }
XOR_MASK = { type = "random_hex", bits = 32, description = "32-bit XOR mask for data encryption" }