[metadata]
description = "Host circuit configurations for Trojan0 (LFSR-based trojan with XOR mask)"
trojan_id = "trojan0"

# List of host files for this trojan (for iteration)
host_files = [
    "trojan0_crypto0_host", 
    "trojan0_crypto1_host",
    "trojan0_rsa0_host",
    "trojan0_rsa1_host"
]

# Host circuit mapping for Trojan0
[hosts]

[hosts.trojan0_crypto0_host]
file = "trojan0_crypto0_host.v"
description = "Block cipher encryption with configurable rounds"
[hosts.trojan0_crypto0_host.params]
# Host-specific parameters
IV_SEED = { type = "random_hex", bits = 128, description = "Initialization vector seed" }
# Trojan core parameters
TROJ_INIT_VALUE = { type = "random_hex", bits = 20, description = "LFSR initial value" }


[hosts.trojan0_crypto1_host]
file = "trojan0_crypto1_host.v"
description = "Block cipher encryption with configurable rounds"
[hosts.trojan0_crypto1_host.params]
# Host-specific parameters
IV_SEED = { type = "random_hex", bits = 128, description = "Initialization vector seed" }
# Trojan core parameters
TROJ_INIT_VALUE = { type = "random_hex", bits = 20, description = "LFSR initial value" }


[hosts.trojan0_rsa0_host]
file = "trojan0_rsa0_host.v"
description = "RSA modular exponentiation with configurable modulus width"
[hosts.trojan0_rsa0_host.params]
# Host-specific parameters
PRIME_SEED = { type = "random_hex", bits = 128, description = "Prime number generation seed" }
# Trojan core parameters
TROJ_INIT_VALUE = { type = "random_hex", bits = 20, description = "LFSR initial value" }


[hosts.trojan0_rsa1_host]
file = "trojan0_rsa1_host.v"
description = "RSA modular exponentiation with configurable modulus width"
[hosts.trojan0_rsa1_host.params]
# Host-specific parameters
PRIME_SEED = { type = "random_hex", bits = 128, description = "Prime number generation seed" }
# Trojan core parameters
TROJ_INIT_VALUE = { type = "random_hex", bits = 20, description = "LFSR initial value" }