[metadata]
description = "Host circuit configurations for Trojan1 (Counter-based trigger)"
trojan_id = "trojan1"

# List of host files for this trojan (for iteration)
host_files = [
    "trojan1_counter0_host",
    "trojan1_counter1_host",
    "trojan1_decoder0_host",
    "trojan1_decoder1_host"
]

# Host circuit mapping for Trojan1
[hosts]

[hosts.trojan1_counter0_host]
file = "trojan1_counter0_host.v"
description = "16-bit up/down counter with overflow detection"
[hosts.trojan1_counter0_host.params]


[hosts.trojan1_counter1_host]
file = "trojan1_counter1_host.v"
description = "16-bit up/down counter with overflow detection"
[hosts.trojan1_counter1_host.params]


[hosts.trojan1_decoder0_host]
file = "trojan1_decoder0_host.v" 
description = "Binary decoder with configurable output count"
# Host-specific parameters
[hosts.trojan1_decoder0_host.params]
LFSR_INIT = { type = "random_hex", bits = 128, description = "Seed for LFSR" }


[hosts.trojan1_decoder1_host]
file = "trojan1_decoder1_host.v"
description = "Binary decoder with configurable output count"
# Host-specific parameters
[hosts.trojan1_decoder1_host.params]
XOR_MASK = { type = "random_hex", bits = 16, description = "XOR mask for decoder" }