[metadata]
description = "Host circuit configurations for Trojan8 (Complex arithmetic with mask operations)"
trojan_id = "trojan8"

# List of host files for this trojan (for iteration)
host_files = [
    "trojan8_dsp_host", 
    "trojan8_vector_host", 
    "trojan8_matrix_host"
]

# Host circuit mapping for Trojan8
[hosts]

[hosts.trojan8_dsp_host]
file = "trojan8_dsp_host.v"
description = "DSP processor with configurable coefficients and pipeline depth"
# Structural parameters
# Structural parameters - converted to fixed constants in host circuit
# COEFF_COUNT = 8 (fixed)
# PIPELINE_DEPTH = 3 (fixed)
# DSP_SEED = fixed constants (fixed)
# No configurable parameters - using fixed design

[hosts.trojan8_vector_host]
file = "trojan8_vector_host.v" 
description = "Vector processor with configurable size and parallel ALUs"
# Structural parameters
# Crypto parameters
[hosts.trojan8_vector_host.crypto_vars]
VEC_PATTERN = { type = "random_hex", bits = 64, description = "Pattern for vector data generation" }

[hosts.trojan8_matrix_host]
file = "trojan8_matrix_host.v"
description = "Matrix processor with configurable dimension and MAC units"
# Structural parameters
# Crypto parameters
[hosts.trojan8_matrix_host.crypto_vars]
MAT_PATTERN = { type = "random_hex", bits = 96, description = "Pattern for matrix data generation" }