[metadata]
description = "Host circuit configurations for Trojan2 (Sequence-based trigger with force reset)"
trojan_id = "trojan2"

# List of host files for this trojan (for iteration)
host_files = [
    "trojan2_processor_host", 
    "trojan2_fifo_host", 
    "trojan2_uart_host",
    "trojan2_counter_host",
    "trojan2_spi_host",
    "trojan2_alu_host",
    "trojan2_timer_host",
    "trojan2_pwm_host"
]

# Host circuit mapping for Trojan2
[hosts]

[hosts.trojan2_processor_host]
file = "trojan2_processor_host.v"
description = "Simple processor with ALU operations and program counter"
[hosts.trojan2_processor_host.params]
# Host-specific parameters
DATA_PATTERN = { type = "random_hex", bits = 16, description = "Pattern for data generation" }
# Trojan core parameters
TROJ_TRIGGER_SEQUENCE_1 = { type = "random_hex", bits = 8, description = "First sequence for trigger" }
TROJ_TRIGGER_SEQUENCE_2 = { type = "random_hex", bits = 8, description = "Second sequence for trigger" }


[hosts.trojan2_fifo_host]
file = "trojan2_fifo_host.v" 
description = "FIFO buffer with configurable depth and data width"
[hosts.trojan2_fifo_host.params]
# Host-specific parameters
SEQUENCE_SEED = { type = "random_hex", bits = 24, description = "Seed for data sequence generation" }
# Trojan core parameters
TROJ_TRIGGER_SEQUENCE_1 = { type = "random_hex", bits = 8, description = "First sequence for trigger" }
TROJ_TRIGGER_SEQUENCE_2 = { type = "random_hex", bits = 8, description = "Second sequence for trigger" }


[hosts.trojan2_uart_host]
file = "trojan2_uart_host.v"
description = "UART transceiver with configurable baud rate"
[hosts.trojan2_uart_host.params]
# Host-specific parameters
TX_PATTERN = { type = "random_hex", bits = 32, description = "Pattern for transmission data generation" }
# Trojan core parameters
TROJ_TRIGGER_SEQUENCE_1 = { type = "random_hex", bits = 8, description = "First sequence for trigger" }
TROJ_TRIGGER_SEQUENCE_2 = { type = "random_hex", bits = 8, description = "Second sequence for trigger" }


[hosts.trojan2_counter_host]
file = "trojan2_counter_host.v"
description = "Configurable up/down counter with overflow detection"
[hosts.trojan2_counter_host.params]
# Host-specific parameters
COUNT_PATTERN = { type = "random_hex", bits = 28, description = "Pattern for data generation" }
# Trojan core parameters
TROJ_TRIGGER_SEQUENCE_1 = { type = "random_hex", bits = 8, description = "First sequence for trigger" }
TROJ_TRIGGER_SEQUENCE_2 = { type = "random_hex", bits = 8, description = "Second sequence for trigger" }


[hosts.trojan2_spi_host]
file = "trojan2_spi_host.v"
description = "SPI master controller with configurable frame width"
[hosts.trojan2_spi_host.params]
# Host-specific parameters
SPI_PATTERN = { type = "random_hex", bits = 24, description = "Pattern for data generation" }
# Trojan core parameters
TROJ_TRIGGER_SEQUENCE_1 = { type = "random_hex", bits = 8, description = "First sequence for trigger" }
TROJ_TRIGGER_SEQUENCE_2 = { type = "random_hex", bits = 8, description = "Second sequence for trigger" }


[hosts.trojan2_alu_host]
file = "trojan2_alu_host.v"
description = "Arithmetic Logic Unit with multiple operations and flags"
[hosts.trojan2_alu_host.params]
# Host-specific parameters
ALU_SEED = { type = "random_hex", bits = 20, description = "Seed for data generation" }
# Trojan core parameters
TROJ_TRIGGER_SEQUENCE_1 = { type = "random_hex", bits = 8, description = "First sequence for trigger" }
TROJ_TRIGGER_SEQUENCE_2 = { type = "random_hex", bits = 8, description = "Second sequence for trigger" }


[hosts.trojan2_timer_host]
file = "trojan2_timer_host.v"
description = "Configurable timer with prescaler and compare match"
[hosts.trojan2_timer_host.params]
# Host-specific parameters
TIMER_SEED = { type = "random_hex", bits = 32, description = "Seed for data generation" }
# Trojan core parameters
TROJ_TRIGGER_SEQUENCE_1 = { type = "random_hex", bits = 8, description = "First sequence for trigger" }
TROJ_TRIGGER_SEQUENCE_2 = { type = "random_hex", bits = 8, description = "Second sequence for trigger" }


[hosts.trojan2_pwm_host]
file = "trojan2_pwm_host.v"
description = "Multi-channel PWM generator with configurable resolution"
[hosts.trojan2_pwm_host.params]
# Host-specific parameters
PWM_PATTERN = { type = "random_hex", bits = 26, description = "Pattern for data generation" }
# Trojan core parameters
TROJ_TRIGGER_SEQUENCE_1 = { type = "random_hex", bits = 8, description = "First sequence for trigger" }
TROJ_TRIGGER_SEQUENCE_2 = { type = "random_hex", bits = 8, description = "Second sequence for trigger" }