[metadata]
description = "Sequence-based reset trigger (I/O fixed: data_in[7:0], force_reset single bit)"

# Trojan core parameters
[crypto_vars.TRIGGER_SEQUENCE_1]
type = "random_hex"
bits = 8
description = "First sequence for trigger"

[crypto_vars.TRIGGER_SEQUENCE_2]
type = "random_hex"
bits = 8
description = "Second sequence for trigger"

