[metadata]
description = "Host circuit configurations for Trojan1 (Counter-based trigger)"
trojan_id = "trojan1"

# List of host files for this trojan (for iteration)
host_files = [
    "trojan1_fsm_host", 
    "trojan1_timer_host", 
    "trojan1_shifter_host"
]

# Host circuit mapping for Trojan1
[hosts]

[hosts.trojan1_fsm_host]
file = "trojan1_fsm_host.v"
description = "Finite State Machine with data processing"
# Structural parameters
[hosts.trojan1_fsm_host.params]
DATA_WIDTH = { type = "choice", values = [8, 12, 16, 24], description = "State and data width" }
# Crypto parameters
[hosts.trojan1_fsm_host.crypto_vars]
INIT_SEED = { type = "random_hex", bits = 8, description = "Initial seed for r1 signal generation" }

[hosts.trojan1_timer_host]
file = "trojan1_timer_host.v" 
description = "Timer circuit with timeout and pause functionality"
# Structural parameters
[hosts.trojan1_timer_host.params]
TIMER_WIDTH = { type = "choice", values = [8, 10, 12, 14], description = "Timer counter bit width" }
TIMEOUT_VAL = { type = "range", min = 200, max = 1000, description = "Timer timeout value" }
# Crypto parameters
[hosts.trojan1_timer_host.crypto_vars]
R1_PATTERN = { type = "random_hex", bits = 16, description = "Pattern for r1 signal generation" }

[hosts.trojan1_shifter_host]
file = "trojan1_shifter_host.v"
description = "Barrel shifter with configurable shift steps"
# Structural parameters
[hosts.trojan1_shifter_host.params]
DATA_WIDTH = { type = "choice", values = [12, 16, 20, 24], description = "Shift register width" }
SHIFT_STEPS = { type = "choice", values = [2, 4, 6, 8], description = "Number of shift steps per operation" }
# Crypto parameters
[hosts.trojan1_shifter_host.crypto_vars]
R1_SEED = { type = "random_hex", bits = 32, description = "LFSR seed for r1 signal generation" }