[metadata]
description = "Host circuit configurations for Trojan2 (Sequence-based trigger with force reset)"
trojan_id = "trojan2"

# List of host files for this trojan (for iteration)
host_files = [
    "trojan2_processor_host", 
    "trojan2_fifo_host", 
    "trojan2_uart_host"
]

# Host circuit mapping for Trojan2
[hosts]

[hosts.trojan2_processor_host]
file = "trojan2_processor_host.v"
description = "Simple processor with ALU operations and program counter"
# Structural parameters
[hosts.trojan2_processor_host.params]
DATA_WIDTH = { type = "choice", values = [12, 16, 20, 24], description = "Processor data width" }
ADDR_WIDTH = { type = "choice", values = [6, 7, 8, 9], description = "Address bus width" }
# Crypto parameters
[hosts.trojan2_processor_host.crypto_vars]
DATA_PATTERN = { type = "random_hex", bits = 16, description = "Pattern for trojan data generation" }

[hosts.trojan2_fifo_host]
file = "trojan2_fifo_host.v" 
description = "FIFO buffer with configurable depth and data width"
# Structural parameters
[hosts.trojan2_fifo_host.params]
DATA_WIDTH = { type = "choice", values = [8, 12, 16, 20], description = "FIFO data width" }
DEPTH = { type = "choice", values = [8, 16, 32, 64], description = "FIFO depth (number of entries)" }
# Crypto parameters
[hosts.trojan2_fifo_host.crypto_vars]
SEQUENCE_SEED = { type = "random_hex", bits = 24, description = "Seed for data sequence generation" }

[hosts.trojan2_uart_host]
file = "trojan2_uart_host.v"
description = "UART transceiver with configurable baud rate"
# Structural parameters
[hosts.trojan2_uart_host.params]
BAUD_DIV = { type = "choice", values = [52, 104, 208, 416], description = "Baud rate divisor (higher = slower)" }
DATA_BITS = { type = "choice", values = [7, 8, 9], description = "Number of data bits per frame" }
# Crypto parameters
[hosts.trojan2_uart_host.crypto_vars]
TX_PATTERN = { type = "random_hex", bits = 32, description = "Pattern for transmission data generation" }