[metadata]
description = "Host circuit configurations for Trojan3 (Counter-based data increment)"
trojan_id = "trojan3"

# List of host files for this trojan (for iteration)
host_files = [
    "trojan3_arithmetic_host", 
    "trojan3_filter_host", 
    "trojan3_cache_host"
]

# Host circuit mapping for Trojan3
[hosts]

[hosts.trojan3_arithmetic_host]
file = "trojan3_arithmetic_host.v"
description = "Pipelined arithmetic unit with multiple operations"
# Structural parameters
# Structural parameters
[hosts.trojan3_arithmetic_host.params]
PIPELINE_STAGES = { type = "choice", values = [2, 3, 4, 5], description = "Number of pipeline stages" }
# Crypto parameters
[hosts.trojan3_arithmetic_host.crypto_vars]
MULT_SEED = { type = "random_hex", bits = 32, description = "Seed for data generation" }

[hosts.trojan3_filter_host]
file = "trojan3_filter_host.v" 
description = "FIR filter with configurable taps and coefficients"
# Structural parameters
# Structural parameters - converted to fixed constants in host circuit
# TAP_WIDTH = 16 (fixed)
# NUM_TAPS = 8 (fixed)
# COEFF_SEED = fixed constants (fixed)
# No configurable parameters - using fixed design

[hosts.trojan3_cache_host]
file = "trojan3_cache_host.v"
description = "Cache memory with configurable size and associativity"
# Structural parameters
# Structural parameters - converted to fixed constants in host circuit
# CACHE_SIZE = 64 (fixed)
# TAG_WIDTH = 4 (fixed) 
# DATA_WIDTH = 16 (fixed)
# ADDR_PATTERN = fixed constants (fixed)
# No configurable parameters - using fixed design